import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class ExcelDataService {
  public dataUnidadMedida: any = [
    {
      ID: 'KG  ',
      DESCRIPCION: 'Kilogram',
    },
    {
      ID: 'PZ    ',
      DESCRIPCION: 'Pieza',
    },
  ];

  public dataUnidadPeso: any = [
    {
      ID: 'UCWT  ',
      DESCRIPCION: 'Hundredweight (UK)',
    },
    {
      ID: 'QU    ',
      DESCRIPCION: 'Quarter',
    },
    {
      ID: 'SN    ',
      DESCRIPCION: 'Stone',
    },
    {
      ID: 'T     ',
      DESCRIPCION: 'Ton (UK)',
    },
    {
      ID: 'OZ    ',
      DESCRIPCION: 'Avoirdupois Ounce',
    },
    {
      ID: 'LB    ',
      DESCRIPCION: 'Libras',
    },
    {
      ID: 'LTN   ',
      DESCRIPCION: 'Long Ton',
    },
    {
      ID: 'CW    ',
      DESCRIPCION: 'Short Hundredweight',
    },
    {
      ID: 'STN   ',
      DESCRIPCION: 'Short Ton',
    },
    {
      ID: 'AF    ',
      DESCRIPCION: 'Centigram',
    },
    {
      ID: 'DG    ',
      DESCRIPCION: 'Decigram',
    },
    {
      ID: 'DK    ',
      DESCRIPCION: 'Dekagram',
    },
    {
      ID: 'GR    ',
      DESCRIPCION: 'Gram',
    },
    {
      ID: 'HG    ',
      DESCRIPCION: 'Hectogram',
    },
    {
      ID: 'KG    ',
      DESCRIPCION: 'Kilogram',
    },
    {
      ID: 'MT    ',
      DESCRIPCION: 'Metric Ton',
    },
    {
      ID: 'ME    ',
      DESCRIPCION: 'Milligram',
    },
  ];

  public dataUOMDimension: any = [
    {
      ID: 'FT    ',
      DESCRIPCION: 'Foot',
    },
    {
      ID: 'FR    ',
      DESCRIPCION: 'Furlong',
    },
    {
      ID: 'IN    ',
      DESCRIPCION: 'Inch',
    },
    {
      ID: 'MI    ',
      DESCRIPCION: 'Mile',
    },
    {
      ID: 'RD    ',
      DESCRIPCION: 'Rod',
    },
    {
      ID: 'YD    ',
      DESCRIPCION: 'Yard',
    },
    {
      ID: 'CMT   ',
      DESCRIPCION: 'Centimeter',
    },
    {
      ID: 'DM    ',
      DESCRIPCION: 'Decimeter',
    },
    {
      ID: 'DCM   ',
      DESCRIPCION: 'Decameter',
    },
    {
      ID: 'HCT   ',
      DESCRIPCION: 'Hectometer',
    },
    {
      ID: 'KM    ',
      DESCRIPCION: 'Kilometer',
    },
    {
      ID: 'MR    ',
      DESCRIPCION: 'Meter',
    },
    {
      ID: 'MM    ',
      DESCRIPCION: 'Millimeter',
    },
  ];

  public dataCasePack: any = [
    {
      CasePackID: '1',
      Proveedor: '10',
      Producto: 'prod',
      Estilo: 'es',
      FactordeEmpaque: 'FacEmp',
      UnidadMedida: 'Um',
      CostoCasePack: 'costo',
      FechaInicioCosto: 'inicio',
      Descripción: 'descripcion',
      NúmerodeInners: 'inners',
      UnidadesporInner: 'inner',
      PesoBruto: 'bruto',
      PesoNeto: 'neto',
      UnidadPeso: 'peso',
      AnchoCaja: 'ancho',
      AltoCaja: 'alto',
      LargoCaja: 'largo',
      UnidadDimensiónCaja: 'dimension',
      EstibaPallet: 'estiba',
      CamadaPallet: 'camada',
      CasePackPrimario: 'primario',
      MúltiploCompra: 'multiplo',
      CompraMínima: 'mini',
    },
    {
      CasePackID: '2',
      Proveedor: '10',
      Producto: 'prod',
      Estilo: 'es',
      FactordeEmpaque: 'FacEmp',
      UnidadMedida: 'Um',
      CostoCasePack: 'costo',
      FechaInicioCosto: 'inicio',
      Descripción: 'descripcion',
      NúmerodeInners: 'inners',
      UnidadesporInner: 'inner',
      PesoBruto: 'bruto',
      PesoNeto: 'neto',
      UnidadPeso: 'peso',
      AnchoCaja: 'ancho',
      AltoCaja: 'alto',
      LargoCaja: 'largo',
      UnidadDimensiónCaja: 'dimension',
      EstibaPallet: 'estiba',
      CamadaPallet: 'camada',
      CasePackPrimario: 'primario',
      MúltiploCompra: 'multiplo',
      CompraMínima: 'mini',
    },
    {
      CasePackID: '3',
      Proveedor: '20',
      Producto: 'prod',
      Estilo: 'es',
      FactordeEmpaque: 'FacEmp',
      UnidadMedida: 'Um',
      CostoCasePack: 'costo',
      FechaInicioCosto: 'inicio',
      Descripción: 'descripcion',
      NúmerodeInners: 'inners',
      UnidadesporInner: 'inner',
      PesoBruto: 'bruto',
      PesoNeto: 'neto',
      UnidadPeso: 'peso',
      AnchoCaja: 'ancho',
      AltoCaja: 'alto',
      LargoCaja: 'largo',
      UnidadDimensiónCaja: 'dimension',
      EstibaPallet: 'estiba',
      CamadaPallet: 'camada',
      CasePackPrimario: 'primario',
      MúltiploCompra: 'multiplo',
      CompraMínima: 'mini',
    },
    {
      CasePackID: '4',
      Proveedor: '20',
      Producto: 'prod',
      Estilo: 'es',
      FactordeEmpaque: 'FacEmp',
      UnidadMedida: 'Um',
      CostoCasePack: 'costo',
      FechaInicioCosto: 'inicio',
      Descripción: 'descripcion',
      NúmerodeInners: 'inners',
      UnidadesporInner: 'inner',
      PesoBruto: 'bruto',
      PesoNeto: 'neto',
      UnidadPeso: 'peso',
      AnchoCaja: 'ancho',
      AltoCaja: 'alto',
      LargoCaja: 'largo',
      UnidadDimensiónCaja: 'dimension',
      EstibaPallet: 'estiba',
      CamadaPallet: 'camada',
      CasePackPrimario: 'primario',
      MúltiploCompra: 'multiplo',
      CompraMínima: 'mini',
    },
    {
      CasePackID: '5',
      Proveedor: '30',
      Producto: 'prod',
      Estilo: 'es',
      FactordeEmpaque: 'FacEmp',
      UnidadMedida: 'Um',
      CostoCasePack: 'costo',
      FechaInicioCosto: 'inicio',
      Descripción: 'descripcion',
      NúmerodeInners: 'inners',
      UnidadesporInner: 'inner',
      PesoBruto: 'bruto',
      PesoNeto: 'neto',
      UnidadPeso: 'peso',
      AnchoCaja: 'ancho',
      AltoCaja: 'alto',
      LargoCaja: 'largo',
      UnidadDimensiónCaja: 'dimension',
      EstibaPallet: 'estiba',
      CamadaPallet: 'camada',
      CasePackPrimario: 'primario',
      MúltiploCompra: 'multiplo',
      CompraMínima: 'mini',
    },
    {
      CasePackID: '6',
      Proveedor: '20',
      Producto: 'prod',
      Estilo: 'es',
      FactordeEmpaque: 'FacEmp',
      UnidadMedida: 'Um',
      CostoCasePack: 'costo',
      FechaInicioCosto: 'inicio',
      Descripción: 'descripcion',
      NúmerodeInners: 'inners',
      UnidadesporInner: 'inner',
      PesoBruto: 'bruto',
      PesoNeto: 'neto',
      UnidadPeso: 'peso',
      AnchoCaja: 'ancho',
      AltoCaja: 'alto',
      LargoCaja: 'largo',
      UnidadDimensiónCaja: 'dimension',
      EstibaPallet: 'estiba',
      CamadaPallet: 'camada',
      CasePackPrimario: 'primario',
      MúltiploCompra: 'multiplo',
      CompraMínima: 'mini',
    },
    {
      CasePackID: '7',
      Proveedor: '30',
      Producto: 'prod',
      Estilo: 'es',
      FactordeEmpaque: 'FacEmp',
      UnidadMedida: 'Um',
      CostoCasePack: 'costo',
      FechaInicioCosto: 'inicio',
      Descripción: 'descripcion',
      NúmerodeInners: 'inners',
      UnidadesporInner: 'inner',
      PesoBruto: 'bruto',
      PesoNeto: 'neto',
      UnidadPeso: 'peso',
      AnchoCaja: 'ancho',
      AltoCaja: 'alto',
      LargoCaja: 'largo',
      UnidadDimensiónCaja: 'dimension',
      EstibaPallet: 'estiba',
      CamadaPallet: 'camada',
      CasePackPrimario: 'primario',
      MúltiploCompra: 'multiplo',
      CompraMínima: 'mini',
    },
    {
      CasePackID: '8',
      Proveedor: '20',
      Producto: 'prod',
      Estilo: 'es',
      FactordeEmpaque: 'FacEmp',
      UnidadMedida: 'Um',
      CostoCasePack: 'costo',
      FechaInicioCosto: 'inicio',
      Descripción: 'descripcion',
      NúmerodeInners: 'inners',
      UnidadesporInner: 'inner',
      PesoBruto: 'bruto',
      PesoNeto: 'neto',
      UnidadPeso: 'peso',
      AnchoCaja: 'ancho',
      AltoCaja: 'alto',
      LargoCaja: 'largo',
      UnidadDimensiónCaja: 'dimension',
      EstibaPallet: 'estiba',
      CamadaPallet: 'camada',
      CasePackPrimario: 'primario',
      MúltiploCompra: 'multiplo',
      CompraMínima: 'mini',
    },
    {
      CasePackID: '9',
      Proveedor: '10',
      Producto: 'prod',
      Estilo: 'es',
      FactordeEmpaque: 'FacEmp',
      UnidadMedida: 'Um',
      CostoCasePack: 'costo',
      FechaInicioCosto: 'inicio',
      Descripción: 'descripcion',
      NúmerodeInners: 'inners',
      UnidadesporInner: 'inner',
      PesoBruto: 'bruto',
      PesoNeto: 'neto',
      UnidadPeso: 'peso',
      AnchoCaja: 'ancho',
      AltoCaja: 'alto',
      LargoCaja: 'largo',
      UnidadDimensiónCaja: 'dimension',
      EstibaPallet: 'estiba',
      CamadaPallet: 'camada',
      CasePackPrimario: 'primario',
      MúltiploCompra: 'multiplo',
      CompraMínima: 'mini',
    },
  ];

  constructor() {}
}
